### ISSUE TITLE
Syncing Categories

### ISSUE THREAD

**Issue by iamlili** [nigelheap/impartmedia-bookeasy-wordpress-plugin#10]
Hi,
I've just started testing you plugin, I'm a bit confused as to how the categories get synced up?

I've managed to import all the operators (with no terms), however the category sync is not working. I get  array_merge(): Argument is not an array warnings, which I'm looking to now.

Am I meant to set up the categories with ACF first?

**Comment by iamlili** [comment]
Hey, i made the following changes in the cats function for it to work.

And now I just have to create all the member-categories and link them up to these imported categories?

```diff
@@ -1034,7 +1034,7 @@ class Import extends Base {
 
                 $result = $this->request(
                     $load,
-                    'Operators',
+                    false,
                     'Operators',
                     $onlySync
                 );
@@ -1046,14 +1046,14 @@ class Import extends Base {
 
             $arr = $this->request(
                 $url,
-                'Operators',
+                false,
                 'Operators',
                 $onlySync
             );
         }
 
         $types = [];
-        foreach($arr as $op){
+        foreach($arr['Operators'] as $op){
 
             // add the rest of the field in to post 
```

**Comment by nigelheap** [comment]
Thanks, I have pushed an update to fix this issue.

The issue was actually in the merge, this:
`$arr['Operators'] = array_merge($arr['Operators'], $result['Operators']);`

Should have been: 
`$arr = array_merge($arr, $result);`
