### ISSUE TITLE
Warning: array_merge(): Argument #3 is not an array

### ISSUE THREAD

**Issue by princebhalani143** [nigelheap/impartmedia-bookeasy-wordpress-plugin#4]
I am getting below error for the [bookeasy_single] shortcode

**Warning:** array_merge(): Argument #3 is not an array in **C:\xampp\htdocs\theme\wp-content\plugins\bookeasy\frontend\shortcodes.php on line 85**

Everything else is working properly, Can you please let me know how I can resolve above error?

**Comment by nigelheap** [comment]
The above commit should fix it

**Comment by princebhalani143** [comment]
I have tried the updated code but it's giving same error on line 87 below code

`$data = array_merge($defaults, $this->options, $atts);`

**Comment by nigelheap** [comment]
The issue isn't on line 87, the issue is the default argument .. please see [my commit](https://github.com/nigelheap/impartmedia-bookeasy-wordpress-plugin/commit/15f7996d59875b3f4f201a548c6d8dbaaabf434e)

**Comment by princebhalani143** [comment]
Thanks for that, I have play with default argument and then it's working but for that I have to reomve productID field and supply vcID manually, templates\single.php file is not picking `vcID:<?php echo $vc_id ?>` from the backend option.

**Comment by nigelheap** [comment]
I have added added a new fix checking if the arg it empty or not.

See 6aa0cd5a8031499f108120f04870c1b9265f3ce0

**Comment by princebhalani143** [comment]
Actually that works smoothly but now under templates\single.php is not picking up productID value

`productID:<?php echo $operatorid; ?>`

**Comment by princebhalani143** [comment]
Can you please suggest me how I can resolve this issue? I have also seen some of your developed website is using new function cart booking timer it's not included in this plugin
