### ISSUE TITLE
Image issues with syncing

### ISSUE THREAD

**Issue by Smittyhead** [nigelheap/impartmedia-bookeasy-wordpress-plugin#7]
every time I sync, all updated photos from bookeasy come in the library just as a 650 byte file, no image

**Comment by nigelheap** [comment]
This should be fixed now

**Comment by Smittyhead** [comment]
updating the plugin breaks all my styling and brings up php errors.  Will test this more later when have time but have rolled it back to the older version.

**Comment by nigelheap** [comment]
My plugin doesn't include any styling, this all comes from bookeasy

**Comment by nigelheap** [comment]
What are the errors you seeing when update the plugin?
