### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by Smittyhead** [nigelheap/impartmedia-bookeasy-wordpress-plugin#8]
Hi,
I have received an email from Bookeasy saying they are upgrading the api,  Are you going to be upgrading the plugin to suit?

**Comment by nigelheap** [comment]
I will be later on next month

**Comment by nigelheap** [comment]
I have pushed this update through today, you will need to add the new api key into the config section of the plugin. 

You can get this key from bookeasy directly
